### ISSUE TITLE
No melpa recipe exists

### ISSUE THREAD

**Issue by credmp** [plexus/html-to-hiccup#6]
Hi,

I tried your instructions on getting the package. I always try to use use-package, as it greatly simplifies things.

I noticed that the package is not included in [elpa](http://elpa.gnu.org/packages/) nor is it in [melpa](https://github.com/melpa/melpa).

What should happen: a pull request should be made to melpa to include a recipe for this package. If I have some time I might create one for the melpa archive.

Regards,

Arjen

**Comment by dotemacs** [comment]
The recipe is due to be included in MELPA, see this PR: 
https://github.com/melpa/melpa/pull/4365

**Comment by credmp** [comment]
awesome, I couldn't find it when I looked this morning. Will close this issue then.

**Comment by plexus** [comment]
Sorry about that, I didn't expect it to take this long to get it into melpa. When I added Chruby.el a few years ago it went much faster. I addressed the last comments there, hopefully someone merges it soon.
